config/routes.rb
Rails.application.routes.draw do
  resources :subject_contents, only: %i[create update destroy]
  resources :subject, only: %i[index show]
  resources :department, only: %i[index show]
  resources :faculties, only: %i[index show]

  get :editor, to: 'subject#editor'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, path: '/', path_names: {
    registration: 'register',
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret'
  }
  root to: 'home#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/faculty.rb
class Faculty < ApplicationRecord
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :subject_contents, dependent: :destroy
end

app/models/subject_content.rb
class SubjectContent < ApplicationRecord
  CONTENT_TYPES = %w[theory exercise test].freeze

  belongs_to :subject

  enum type: CONTENT_TYPES
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/department_controller.rb
class DepartmentController < ApplicationController
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/subject_contents_controller.rb
class SubjectContentsController < ApplicationController
  def create; end

  def update; end

  def destroy; end
end

app/controllers/subject_controller.rb
class SubjectController < ApplicationController
  def index
  end

  def editor
    respond_to do |format|
      format.js { render layout: false, locals: { type: params[:editor] } }
    end
  end

  def show; end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/subject_contents_helper.rb
module SubjectContentsHelper
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/views/subject/_editor.html.erb
<div class="container">
  <h3><%= "#{type} editor".upcase %></h3>

  <%= form_tag subject_contents_path, method: :post do %>
    <%= hidden_field_tag 'type', type %>
    <div class="row">
      <div class="col-md-1">
        <%= submit_tag 'Save', class: 'btn btn-success'%>
      </div>
    </div>

    <br />

    <div class="row">
      <div class="col-md-12">
        <%= text_area_tag :editor %>
      </div>
    </div>
  <% end %>
</div>

app/views/subject/_sidebar.html.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
  <div class="sidebar-sticky">
    <ul class="nav flex-column">
      <li class="nav-item">
        <a class="nav-link active" href="#">
          Dashboard
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          Orders
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          Products
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          Customers
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          Reports
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          Integrations
        </a>
      </li>
    </ul>
  </div>
</nav>

app/views/subject/editor.js.erb
$("#content").html("<%= escape_javascript(render partial: "editor", locals: { type: :"#{type}"}) %>");
$('#editor').froalaEditor();

app/views/subject/index.html.erb
<%= link_to :add_theory, editor_path(editor: :theory), remote: true %>
<%= link_to :add_exercise, editor_path(editor: :exercise), remote: true %>

<div id="content">
</div>